name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Go Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Configure CGO
        run: echo "CGO_ENABLED=1" >> $GITHUB_ENV

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/log6301-php-parser-${{ matrix.goos }}-${{ matrix.goarch }}${{(matrix.goos == 'windows' && matrix.goarch == 'amd64') && '.exe' }} .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/*
